### ISSUE TITLE
bnetserver.exe & worldserver.exe close almost instantly?

### ISSUE THREAD

**Issue by Michael-Brewer** [ProjectSkyfire/SkyFire.406a#955]
(this is for running a wow 6.2.3 private server.)
When ever I open bnetserver.exe and worldserver.exe this is the only thing it says before it auto closes...

bnetserver.exe -

Project Wodcore 2014-2016(c) Warlords of Dreanor Patch 6.2.3.20886
Using configuration file bnetserver.conf.
Using SSL version: OpenSSL 1.0.1j 15 Oct 2014 (library: OpenSSL 1.0.2d 9 Jul 2015)
Using Boost version: 1.59.0
Automatic database updates are disabled for all databases!
Opening Databasepool 'auth'. Asynchronous connections: 1, synchronous connections: 1.

worldserver.exe - 

Project Wodcore 2014-2016(c) Warlords of Dreanor Patch 6.2.3.20886
Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.0.1j 15 Oct 2014 (library: OpenSSL 1.0.2d 9 Jul 2015)
Using Boost version: 1.59.0
Automatic database updates are disabled for all databases!

The dbc, maps, nmaps, and vmaps are in the core folder and im running mysql.exe...

can someone help with this?

**Comment by Michael-Brewer** [comment]
I got it fixed!

**Comment by SkyFire** [comment]
Glad you closed it. It would have never been supported by us.
